[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
numReplicas = 1
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "always"

[service]
internalPort = 8001
